---
- name: Configure Web Servers with SSL
  hosts: web_servers
  become: yes

  tasks:
    # ... Other tasks (HTTP configuration, website deployment)

    - name: Ensure SSL certificate directory exists
      file:
        path: /etc/ssl/private
        state: directory

    - name: Copy SSL certificate (HTTPS)
      copy:
        src: /path/to/example.com.crt  # Replace with the actual path to your self-signed certificate
        dest: /etc/ssl/private/example.com.crt
      notify: restart nginx

    - name: Copy SSL private key (HTTPS)
      copy:
        src: /path/to/example.com.key  # Replace with the actual path to your private key
        dest: /etc/ssl/private/example.com.key
      notify: restart nginx


---
- name: Configure Web Servers with SSL
  hosts: web_servers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx

    - name: Configure Nginx Virtual Host (HTTP)
      template:
        src: nginx-vhost.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx

    - name: Deploy Sample Website
      copy:
        src: index.html
        dest: /var/www/html/

    - name: Install SSL certificate (HTTPS)
      copy:
        src: ssl/example.com.crt
        dest: /etc/ssl/certs/
      notify: restart nginx

    - name: Install SSL private key
      copy:
        src: ssl/example.com.key
        dest: /etc/ssl/private/
      notify: restart nginx

    - name: Configure Nginx Virtual Host (HTTPS)
      template:
        src: nginx-vhost-ssl.conf.j2
        dest: /etc/nginx/sites-available/default-ssl
      notify: restart nginx
